build.rs, src/lib.rs
Compile the library and issue a local warning, but otherwise just
pretend as if this library doesn't exist.
=> Make unsupported platforms a noop

.github/workflows/psm.yml, .github/workflows/stacker.yml, psm/Cargo.toml
The ISC and MIT licenses are equivalent, however the ISC license is not
white-listed for use in the rustc compiler, whereas the MIT one is.
As I’m the sole author of psm, no third parties need to be involved in
the decision to execute the re-license.
=> Relicense psm from ISC/Apache-2.0 to MIT/Apache-2.0

Cargo.toml, src/lib.rs
As of recently it is no longer sufficient to just build the `libX.a`
with the cc crate in build.rs. Due to
https://github.com/rust-lang/rust/issues/65610 it is also necessary to
specify the fact of linkage in the source for it to work in all
scenarios. The most frustrating part is that it only fails when shared
libraries are in the equation, which is a comparatively rare use-case in
Rust-land.
=> Specify the external library we link to on Windows

src/lib.rs
This PR addresses a build error that occurs whenever the `psm_stack_information!` macro returns `no` instead of `yes`, as in when targeting `wasm32-unknown-unknown`.  The return types for `current_stack_ptr()` differ between these macro results, being `usize` and `Option<usize>` respectively.
=> Fix mismatched return types in `current_stack_ptr()`

psm/src/lib.rs
cc https://github.com/rust-lang/stacker/issues/30
I think it's linker bug but removing that inline fixed i686 rustdoc build.
=> Workaround Rust build issue for i686 windows-gnu

src/lib.rs
as there is two guard pages used (one on top, and another on bottom), two additionnals guard pages needs to be allocated.
=> allocate 2 pages more than requested for guard pages

psm/build.rs
Currently building with Windows ARM64 as a target fails since the assembler (armasm64.exe) doesn't understand the "-D..." config flags. If these aren't set it builds without issue. I've changed it so they're not set for any MSVC target since none of the other MSVC targets use of the flags anyway, but can change it so it's limited only to aarch64-pc-windows-msvc.
=> Fix build for aarch64-pc-windows-msvc target

psm/src/arch/aarch64_armasm.asm, psm/src/arch/arm_armasm.asm
Closes #37
The directive `AREA CODE, READONLY` was creating a section named `CODE` that was non-executable when built for aarch64-pc-windows-msvc.
This change names the `.text` section ensuring the `CODE` attribute is applied.
=> Use .text as the section name for area directives in armasm files

psm/src/arch/x86_windows_gnu.s
All but the label were `@16`, but the label itself was `@20`.  This was causing an error trying to build a mingw-w64 (windows-gnu) rust using clang/lld.
=> fix fastcall mangling for rust_psm_on_stack

.github/workflows/test.yml
At some point Github decided to no longer install mingw gcc/clang
packages. So much for backwards compatibility eh.
=> Fix MinGW based CI workflows

psm/build.rs
This breaks cross-compilation via "-target X" set in CFLAGS.
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
=> Don't ignore CFLAGS.

psm/build.rs, psm/src/arch/aarch_aapcs64.s, psm/src/lib.rs
Rust PR for the target: https://github.com/rust-lang/rust/pull/94872
First commit disables linking `psm_s` when it's absent since assembly is not compiled.
=> Add `aarch64-*-windows-gnu*` support

psm/README.mkd, psm/build.rs, psm/src/arch/loongarch64.s
The LoongArch architecture (LoongArch) is an Instruction Set
Architecture (ISA) that has a Reduced Instruction Set Computer (RISC)
style.
The documents are on
https://loongson.github.io/LoongArch-Documentation/README-EN.html
The ELF ABI Documents are on:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
I'm not sure if a PR for new target can be reviewed before it can be targeted by rustc.  If not I'll convert this into a draft.
=> psm: Add loongarch64 support

psm/build.rs
The musl libc uses ELFv2 (OpenPOWER ABI) on both big and little endian
64-bit PowerPC targets.  Before this change, running `cargo test` on a
powerpc64-foxkit-linux-musl host showed a SIGSEGV.  Now all tests pass.
=> psm: Use OpenPOWER ABI on BE PowerPC 64/musl

psm/src/arch/riscv.s, psm/src/arch/riscv64.s
We used RISC-V code as a reference implementing psm for LoongArch.
During the review of LoongArch code we found that the .cfi directives in
RISC-V was incorrect [1].
The GNU assembler defines .cfi_def_cfa [2]:
computing CFA as: take address from register and add offset to it.
So ".cfi_def_cfa x2, 16" will compute the CFA correctly, but we used
"-16".  I tested the code on an StarFive VisionFive v1 board (access
provided by The GCC Compile Farm project [3]) with a C caller and GDB.
GDB indeed reported "corrupt stack" for backtrace.
Fix the symbol of offset to make the backtrace working.  And, clean up
the .cfi directives as Simonas suggested [4].
[1]: https://github.com/rust-lang/stacker/pull/68#discussion_r862342482
[2]: https://sourceware.org/binutils/docs/as/CFI-directives.html
[3]: …
=> psm: fix .cfi directives for RISC-V

psm/README.mkd, psm/build.rs, psm/src/arch/powerpc64_aix.s
We are porting Rust to AIX, see https://github.com/rust-lang/compiler-team/issues/553. This PR adds corresponding assembly in psm for AIX.
=> [AIX] Port to 64-bit AIX

Cargo.toml, src/lib.rs
Migrate from `winapi` to `windows-rs` for the following:
1. [Winapi is no longer actively](https://github.com/retep998/winapi-rs/issues/867 ) maintained (last commit was 9 months ago as of now and 2nd last around 2 years ago) compared to last commit to [windows-rs ](https://github.com/microsoft/windows-rs)as of few days ago.
2. [windows-rs](https://github.com/microsoft/windows-rs) is the official Rust crate for Windows by Microsoft and is supposed to be providing a natural and idiomatic way for Rust developers to call Windows APIs. Some crates like [socket2](https://github.com/rust-lang/socket2) have already migrated to it.
We can also use the latest version of `windows_sys` (which is `rust-version = "1.46"`) if the minimum required version is changed in ci/cd.
=> migrate from winapi to windows_sys

Cargo.toml, src/lib.rs
Uses the same logic as FreeBSD and DragonflyBSD.
Requires the latest version of libc, which has https://github.com/rust-lang/libc/pull/3788 included.
I've verified locally on an illumos machine that stacker is able to:
* find the right stack size, and
* create new stack segments when running low.
=> [illumos] enable guess_os_stack_limit

Cargo.toml, tests/simple.rs
The new release after #93 finally exposes the migration from #76 to a wider audience... but the windows-sys version used is now long out of date, leading to duplicate dependencies for windows-sys and all the windows-targets crates. Bump the range to allow more modern versions, including 0.52 (currently used by mio) and 0.59 (newest).
=> Bump windows

psm/build.rs, psm/src/lib.rs
Currenty, when using the `asm` configuration, the `lib.rs` file will manually add a `link("psm_s")` attribute to the build causing a flag like `-lpsm_s` to appear on the link line. `psm_s` is the library of assembly code, built by `build.rs` in Cargo projects.
However, when using Cargo packages with build systems like Buck2, we have to manually replace the `build.rs` script, and build the bits of C/assembly code that come with `psm` and `stacker` as a separate build item (an actual library), then link them into the Rust libraries.
The name of the library often can't be easily made identical to `psm_s` as desired by the `link()` call, but we're building and explicitly linking the library anyway, removing the need for this.
Therefore, introduce a new `asm_manual_link` cfg option to give …
=> psm: allow manual opt out of `#cfg[link("psm_s")]`

psm/src/arch/aarch_aapcs64.s, psm/src/arch/x86_64.s
On macOS targets, don't define the symbol `rust_psm_on_stack_end` since it isn't used (and somehow this causes the build to fail).
Fixes #87
=> fix: avoid macOS linker error for rust_psm_on_stack_end

Cargo.toml, psm/Cargo.toml
Closes https://github.com/rust-lang/stacker/issues/100
=> Bump cc dependency

psm/src/arch/aarch_aapcs64.s
See https://github.com/rust-lang/stacker/pull/65#issuecomment-2466601600
=> fix: make Windows AArch64 asm buildable again

Cargo.toml, psm/Cargo.toml, psm/build.rs, src/lib.rs
Fixes https://github.com/rust-lang/stacker/issues/112
=> Support running on miri

src/alloc_stack_restore_guard.rs, src/lib.rs, src/mmap_stack_restore_guard.rs
This implements stacker on hermit by treating it the same as wasm32
=> treat hermit like wasm32

src/mmap_stack_restore_guard.rs
This fixes the memory protection on new stack allocations via mmap. Previously, the accessible range was 1 page too long, reaching all the way to the end of the allocation without the intended guard page.
This issue was briefly discussed in #109.
=> fix high guard page

psm/build.rs
=> Add cygwin support

Cargo.toml, src/lib.rs
Sounds like it is plausible for the stack pointer to end up past the computed stack limit depending on the implementation of stack growing and the exact timing at which the stack limit is determined.
Supersedes #51
=> stacker: make remaining stack computation more resilient
